Storage/StorageMVC/Controllers/AddController.cs
using LegoMVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using StorageMVC.Data;

namespace StorageMVC.Controllers
{
    public class AddController : Controller
    {
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly LegoContext _dbContext;

        public AddController(IWebHostEnvironment webHostEnvironment, LegoContext dbContext)
        {
            _webHostEnvironment = webHostEnvironment;
            _dbContext = dbContext;
        }

        public ActionResult Create()
        {
            var model = new LegoModel();

            model.SeriesList = new List<SelectListItem>
            {
                new SelectListItem { Value = "Series1", Text = "LEGO® Architecture" },
                new SelectListItem { Value = "Series2", Text = "LEGO® Art" },
                new SelectListItem { Value = "Series3", Text = "LEGO® BrickHeadz" },
           
                new SelectListItem { Value = "DefSeries", Text = "Other" }
            };

            model.WarehousesList = new List<SelectListItem>
            {
                new SelectListItem { Value = "Warehouse1", Text = "Warehouse 1" },
                new SelectListItem { Value = "Warehouse2", Text = "Warehouse 2" }
            };

            return View("~/Views/Lego/AddLego.cshtml", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateSet(LegoModel legoModel, IFormFile photo)
        {
            if (ModelState.IsValid)
            {
                if(photo != null && photo.Length > 0)
                {
                    string uploadsFolder = Path.Combine(_webHostEnvironment.WebRootPath, "images");
                    string uniqueFileName = Guid.NewGuid().ToString() + "_" + photo.FileName;
                    string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                    using (var fileStream = new FileStream(filePath, FileMode.Create))
                    {
                        await photo.CopyToAsync(fileStream);
                    }

                    legoModel.PhotoPath = "/images/" + uniqueFileName; 
                }
                
                _dbContext.LegoStorage.Add(legoModel);
                await _dbContext.SaveChangesAsync();

                return RedirectToAction("StorageAll", "Display");
            }
            else
            {
                return View("~/Views/Lego/AddLego.cshtml", legoModel);
            }
        }

    }
}

Storage/StorageMVC/Controllers/LegoController.cs
using Microsoft.AspNetCore.Mvc;

namespace StorageMVC.Controllers;

public class LegoController : Controller
{
    //private readonly IConfiguration _configuration;
    private readonly string _filePath;

    public LegoController(IConfiguration configuration)
    {
        _filePath = configuration["FilePath"];
    }
    //public ActionResult Index()
    //{
    //    return View();
    //}

    //public ActionResult StorageAll()
    //{

    //    //string filePath = _configuration["FilePath"];
    //    string savedLego = System.IO.File.ReadAllText(_filePath);

    //    var dataList = JsonConvert.DeserializeObject<List<LegoModel>>(savedLego);

    //    return View("DisplayAll", dataList);
    //}

    //// GET: LegoController/Details/5
    //public ActionResult Details(int id)
    //{
    //    return View();
    //}

    //// GET: LegoController/Edit/5
    //public ActionResult Edit(int id)
    //{
    //    List<LegoModel> legoSets = GetLegoSets();
    //    LegoModel legoSetToEdit = legoSets.FirstOrDefault(s => s.SetNumber == id.ToString());

    //    return View("EditLego", legoSetToEdit);
    //}

    //// POST: LegoController/Delete/5
    //[HttpPost]
    //[ValidateAntiForgeryToken]
    //public ActionResult Delete(int id)
    //{
    //    string savedLego = System.IO.File.ReadAllText(_filePath);

    //    List<LegoModel> dataList = JsonConvert.DeserializeObject<List<LegoModel>>(savedLego);

    //    LegoModel legoToRemove = dataList.FirstOrDefault(l => l.SetNumber == id.ToString());

    //    if (legoToRemove != null)
    //    {
    //        dataList.Remove(legoToRemove);

    //        string updatedLegoSet = JsonConvert.SerializeObject(dataList, Formatting.Indented);

    //        System.IO.File.WriteAllText(_filePath, updatedLegoSet);
    //    }
    //    return RedirectToAction("StorageAll");
    //}

    //private List<LegoModel> GetLegoSets()
    //{
    //    List<LegoModel> legoSets;
    //    if (System.IO.File.Exists(_filePath))
    //    {
    //        string json = System.IO.File.ReadAllText(_filePath);
    //        legoSets = JsonConvert.DeserializeObject<List<LegoModel>>(json);
    //    }
    //    else
    //    {
    //        legoSets = new List<LegoModel>();
    //    }
    //    return legoSets;
    //}
    //private void SaveLegoSets(List<LegoModel> legoSets)
    //{
    //    string json = JsonConvert.SerializeObject(legoSets, Formatting.Indented);
    //    System.IO.File.WriteAllText(_filePath, json);
    //}
    //[HttpPost]
    //[ValidateAntiForgeryToken]
    //public ActionResult CreateSet(LegoModel legoModel)
    //{
    //    var legoSets = GetLegoSets();

    //    //var decimalPrice = decimal.Parse(legoModel.RetailPrice, CultureInfo.InvariantCulture);

    //    legoSets.Add(legoModel);
    //    SaveLegoSets(legoSets);

    //    return RedirectToAction("StorageAll");
    //}
}

Storage/StorageMVC/Controllers/SearchController.cs
using LegoMVC.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using LegoMVC.Model;
using StorageMVC.Data;

namespace StorageMVC.Controllers;

public class SearchController : Controller
{
    private readonly LegoContext _context;

    public SearchController(LegoContext context)
    {
        _context = context;
    }

    public IActionResult Search(string input)
    {
        var legoSetToFind = _context.LegoStorage.FirstOrDefault(s => s.SetName.ToLower().Contains(input.ToLower()));

        return View("~/Views/Lego/SearchResults.cshtml", legoSetToFind);
    }
}

//public class SearchController : Controller
//{
//    private readonly SharedServices _sharedService;

//    public SearchController(SharedServices sharedService)
//    {
//        _sharedService = sharedService;
//    }

//    public ActionResult Search(string input)
//    {
//        List<LegoModel> legoSets = _sharedService.GetLegoSets();
//        LegoModel legoSetToFind = legoSets.FirstOrDefault(s => s.SetName.ToLower().Contains(input.ToLower()));

//        return View("~/Views/Lego/SearchResults.cshtml", legoSetToFind);
//    }
//}

Storage/StorageMVC/Views/Lego/AddLego.cshtml
@model LegoMVC.Models.LegoModel

<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" type="text/css" href="~/css/site.css" />
    <title>AddLego</title>
    <style>
        body {
            background-color: #f0f0f0;
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
        }

        h1, h4 {
            color: #333;
            text-align: center;
            margin: 20px 0;
        }

        .row {
            display: flex;
            justify-content: center;
        }

        .col-md-4 {
            width: 50%;
            margin: 0 auto;
        }

        .form-group {
            margin-bottom: 20px;
        }

        label {
            display: block;
            margin-bottom: 5px;
        }

        input[type="text"],
        input[type="date"],
        select {
            width: 100%;
            padding: 10px;
            font-size: 16px;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
        }

        .btn-primary {
            background-color: #4CAF50;
            border: none;
            color: white;
            padding: 10px 20px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
            margin: 4px 2px;
            cursor: pointer;
            border-radius: 4px;
            transition-duration: 0.4s;
        }

        .btn-primary:hover {
            background-color: #45a049;
        }
    </style>
</head>
<body>
    <h1>AddLego</h1>
    <h4>LegoModel</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
                <form asp-controller="Add" asp-action="CreateSet" method="post">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="SetName" class="control-label">Set Name</label>
                        <input asp-for="SetName" class="form-control" />
                        <span asp-validation-for="SetName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="SetNumber" class="control-label">Set Number</label>
                        <input asp-for="SetNumber" class="form-control" />
                        <span asp-validation-for="SetNumber" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="SelectedSeries" class="control-label">Series</label>
                        <select asp-for="SelectedSeries" class="form-control" asp-items="@(new SelectList(Model.SeriesList, "Value", "Text"))">
                            <option value="">Select Series</option>
                        </select>
                        <span asp-validation-for="SelectedSeries" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="ElementsQuantity" class="control-label">Elements Quantity</label>
                        <input asp-for="ElementsQuantity" class="form-control" data-val="true" data-val-integer="The field Elements Quantity must be an integer." />
                        <span asp-validation-for="ElementsQuantity" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="ReleaseDate" class="control-label">Release Date</label>
                        <input asp-for="ReleaseDate" class="form-control" type="date" />
                        <span asp-validation-for="ReleaseDate" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="RetailPrice" class="control-label">Retail Price</label>
                        <input asp-for="RetailPrice" class="form-control" />
                        <span asp-validation-for="RetailPrice" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="SelectedWarehouse" class="control-label">Warehouse</label>
                        <select asp-for="SelectedWarehouse" class="form-control" asp-items="@(new SelectList(Model.WarehousesList, "Value", "Text"))">
                            <option value="">Select Warehouse</option>
                        </select>
                        <span asp-validation-for="SelectedWarehouse" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Photo" class="control-label"></label>
                        <div class="custom-file">
                            <input asp-for="Photo" class="custom-file-input" id="customFile">
                          
                        </div>
                        <span asp-validation-for="Photo" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="CreateSet" class="btn btn-primary" />
                    </div>
                
            </form>
        </div>
    </div>
</body>
</html>

Storage/StorageMVC/Views/Lego/DeleteConfirmation.cshtml
@model int

<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" type="text/css" href="~/css/site.css" />
    <title>Delete Confirmation</title>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#btnYes').click(function () {
                var id = $('#setNumber').val();
                location.href = '/Delete/DeleteConfirmed/' + id;
            });
            $('#btnNo').click(function () {
                window.history.back();
            });
        });
    </script>

    <style>
        body {
            background-color: #f0f0f0;
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
        }

        h2 {
            color: #333;
            text-align: center;
            margin: 20px 0;
        }

        p {
            text-align: center;
        }

        form {
            text-align: center;
        }

        button {
            background-color: #4CAF50;
            border: none;
            color: white;
            padding: 10px 20px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
            margin: 4px 2px;
            transition-duration: 0.4s;
            cursor: pointer;
        }
        button-

            button:hover {
                background-color: #45a049;
            }
    </style>
</head>
<body>
    <h2>Delete Confirmation</h2>
    <p>Are you sure you want to delete?</p>
    <form method="post" action="/Delete/DeleteConfirmed/@Model">
        @Html.AntiForgeryToken()
        <input type="hidden" id="setNumber" value="@Model" />
        <button type="submit" id="btnYes">Yes</button>
        <button id="btnNo" style="background-color: red;">No</button>

    </form>
</body>
</html>

Storage/StorageMVC/Views/Lego/Details.cshtml
@model LegoMVC.Models.LegoModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>LegoSet</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.SetName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.SetName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.SetNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.SetNumber)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.SelectedSeries)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.SelectedSeries)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ElementsQuantity)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ElementsQuantity)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ReleaseDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ReleaseDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.RetailPrice)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.RetailPrice)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ResellPrice)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ResellPrice)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Warehouse)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Warehouse)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-controller="Display" asp-action="StorageAll">Back to List</a>
</div>

Storage/StorageMVC/Views/Lego/DisplayAll.cshtml
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" type="text/css" href="~/css/site.css" />
    <title>Data View</title>
    <style>
        body {
            background-color: #f0f0f0;
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
        }

        h1, h2 {
            color: #333;
            text-align: center;
            margin: 20px 0;
        }

        table {
            margin: 0 auto;
            border-collapse: collapse;
            width: 80%;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
            background-color: #fff;
        }

        th, td {
            border: 1px solid #ddd;
            padding: 12px;
            text-align: left;
        }

        th {
            background-color: #f2f2f2;
            color: #333;
        }

        tr:hover {
            background-color: #f5f5f5;
        }

        td img {
            display: block;
            margin: 0 auto;
        }

        button {
            background-color: #4CAF50;
            border: none;
            color: white;
            padding: 10px 20px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
            margin: 4px 2px;
            transition-duration: 0.4s;
            cursor: pointer;
        }

            button:hover {
                background-color: #45a049;
            }

        .search-container {
            text-align: center;
            margin-bottom: 20px;
        }

            .search-container input[type=text] {
                padding: 10px;
                margin: 0 auto;
                width: 50%;
                border: 1px solid #ccc;
                border-radius: 4px;
                box-sizing: border-box;
            }

            .search-container button {
                padding: 10px 20px;
                background-color: #2196F3;
                color: white;
                border: none;
                border-radius: 4px;
                cursor: pointer;
            }

                .search-container button:hover {
                    background-color: #0b7dda;
                }
    </style>
</head>
<body>
    <h1>Lego Sets List:</h1>
    <div style="text-align: center;">
        <button type="button" onclick="location.href='@Url.Action("Create", "Add")'">Add Set</button>
    </div>

    <div class="search-container">
        <form asp-controller="Search" asp-action="Search" method="get">
            <input type="text" placeholder="Search for set name.." name="input" id="input">
            <button type="submit">Search</button>
        </form>
    </div>

    <table>
        <tr>
            <th style="width: 200px;">Set Name</th>
            <th>Set Number</th>
            <th style="width: 200px;">Series</th>
            <th>Elements Quantity</th>
            <th style="width: 150px;">Release Date</th>
            <th>Retail Price</th>
            <th>Resell Price</th>
            <th>Warehouse</th>
            <th style="width: 250px;">Actions</th>
        </tr>
        @if (Model != null)
        {
            foreach (var item in Model)
            {
                <tr>
                    <td>@item.SetName</td>
                    <td>@item.SetNumber</td>
                    <td>@item.SelectedSeries</td>
                    <td>@item.ElementsQuantity</td>
                    <td>@item.ReleaseDate.ToString("yyyy-MM-dd")</td>
                    <td>@item.RetailPrice</td>
                    <td>@item.ResellPrice</td>
                    <td>@item.Warehouse</td>
                    <td>
                        <button onclick="location.href='@Url.Action("Delete", "Delete", new { id = item.SetNumber })'">Delete</button>
                        <button onclick="location.href='@Url.Action("Edit", "Edit", new { id = item.SetNumber })'">Edit</button>
                    </td>
                </tr>
            }
        }
        else
        {
            <tr>
                <td colspan="10" style="text-align: center;">No data available</td>
            </tr>
        }
    </table>

</body>
</html>

Storage/StorageMVC/Views/Lego/EditLego.cshtml
@model LegoMVC.Models.LegoModel

@{
    ViewData["Title"] = "EditLego";
}

<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" type="text/css" href="~/css/site.css" />
    <title>EditLego</title>
    <style>
        body {
            background-color: #f0f0f0;
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
        }

        h1, h4 {
            color: #333;
            text-align: center;
            margin: 20px 0;
        }

        .row {
            display: flex;
            justify-content: center;
        }

        .col-md-4 {
            width: 50%;
            margin: 0 auto;
        }

        .form-group {
            margin-bottom: 20px;
        }

        label {
            display: block;
            margin-bottom: 5px;
        }

        input[type="text"],
        input[type="date"],
        select {
            width: 100%;
            padding: 10px;
            font-size: 16px;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
        }

        .btn-primary {
            background-color: #4CAF50;
            border: none;
            color: white;
            padding: 10px 20px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
            margin: 4px 2px;
            cursor: pointer;
            border-radius: 4px;
            transition-duration: 0.4s;
        }

            .btn-primary:hover {
                background-color: #45a049;
            }
    </style>
</head>
<body>
    <h1>EditLego</h1>
    <h4>LegoModel</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="EditLego">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="SetName" class="control-label">Set Name</label>
                    <input asp-for="SetName" class="form-control" />
                    <span asp-validation-for="SetName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="SetNumber" class="control-label">Set Number</label>
                    <input asp-for="SetNumber" class="form-control" />
                    <span asp-validation-for="SetNumber" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="SelectedSeries" class="control-label">Series</label>
                    <input asp-for="SelectedSeries" class="form-control" data-val="true" data-val-integer="The field Series must be an integer." />
                    <span asp-validation-for="SelectedSeries" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ElementsQuantity" class="control-label">Elements Quantity</label>
                    <input asp-for="ElementsQuantity" class="form-control" data-val="true" data-val-integer="The field Elements Quantity must be an integer." />
                    <span asp-validation-for="ElementsQuantity" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ReleaseDate" class="control-label">Release Date</label>
                    <input asp-for="ReleaseDate" class="form-control" type="date" />
                    <span asp-validation-for="ReleaseDate" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="RetailPrice" class="control-label">Retail Price</label>
                    <input asp-for="RetailPrice" class="form-control" />
                    <span asp-validation-for="RetailPrice" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ResellPrice" class="control-label">Resell Price</label>
                    <input asp-for="ResellPrice" class="form-control" />
                    <span asp-validation-for="ResellPrice" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Warehouse" class="control-label">Warehouse</label>
                    <input asp-for="Warehouse" class="form-control" />
                    <span asp-validation-for="Warehouse" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
</body>
</html>

Storage/StorageMVC/Views/Lego/SearchResults.cshtml
@model LegoMVC.Models.LegoModel

@if(Model != null)
{
    <h2>
       Results found:
    </h2>
    <div>
        <h4>Set name: @Model.SetName</h4>
        <p>Set number: @Model.SetNumber</p>
        <p>Set series: @Model.SelectedSeries </p>
        <p>Warehouse: @Model.Warehouse</p>
    </div>
}
else
    {
        <p>No matching item found.</p>
    }